import { css } from '@emotion/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { staticPath } from '@/lib/$path'
import { sp } from '@/styles/media-query'

const Home: NextPage = () => {
  return (
    <div
      css={css`
        padding: 0 2rem;
        background-color: var(--color-primary);
        color: var(--color-white);
      `}
    >
      <Head>
        <title>Nextjs latest starter</title>
        <meta name="description" content="Generated by nextjs latest starter" />
        <link rel="icon" href={staticPath.favicon_ico} />
      </Head>

      <main
        css={css`
          display: flex;
          min-height: 100vh;
          flex: 1;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 4rem 0;
        `}
      >
        <h1
          css={css`
            margin: 0;
            font-size: 4rem;
            line-height: 1.15;
            text-align: center;
          `}
        >
          <a
            href="https://nextjs.org"
            css={css`
              color: var(--color-accent);
              text-decoration: none;
            `}
          >
            Next.js
          </a>{' '}
          latest starter
        </h1>

        <p
          css={css`
            margin: 4rem 0;
            font-size: 1.5rem;
            line-height: 1.5;
            text-align: center;
          `}
        >
          Get started by editing{' '}
          <code
            css={css`
              padding: 0.75rem;
              background: var(--color-base);
              border-radius: 5px;
              color: var(--color-primary);
              font-family: Menlo, Monaco, 'Lucida Console', 'Liberation Mono',
                'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Courier New',
                monospace;
              font-size: 1.1rem;
            `}
          >
            pages/index.tsx
          </code>
        </p>

        <div
          css={css`
            display: flex;
            max-width: 800px;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;

            ${sp} {
              width: 100%;
              flex-direction: column;
            }
          `}
        >
          <Card href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>

          <Card href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </Card>
        </div>
      </main>

      <footer
        css={css`
          display: flex;
          flex: 1;
          align-items: center;
          justify-content: center;
          padding: 2rem 0;
          border-top: 1px solid var(--color-base);
        `}
      >
        <a
          href="https://github.com/tsuki-lab"
          target="_blank"
          rel="noopener noreferrer"
          css={css`
            display: flex;
            flex-grow: 1;
            align-items: center;
            justify-content: center;
          `}
        >
          by hanetsuki
        </a>
      </footer>
    </div>
  )
}

export default Home

export const Card: React.FC<JSX.IntrinsicElements['a']> = ({
  children,
  ...props
}) => (
  <a
    {...props}
    css={css`
      max-width: 300px;
      padding: 1.5rem;
      border: 1px solid var(--color-secondary);
      margin: 1rem;
      border-radius: 10px;
      color: inherit;
      text-align: left;
      text-decoration: none;
      transition: color 0.15s ease, border-color 0.15s ease;

      &:hover,
      &:focus,
      &:active {
        border-color: var(--color-accent);
        color: var(--color-accent);
      }

      h2 {
        margin: 0 0 1rem;
        font-size: 1.5rem;
      }

      p {
        margin: 0;
        font-size: 1.25rem;
        line-height: 1.5;
      }
    `}
  >
    {children}
  </a>
)
